server:
  port: 9003

spring:
  application:
    name: blog-comment
  data:
    mongodb:
      host: localhost
      database: blog-microservice

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka

spring.sleuth.sampler.percentage: 1.0