server:
  port: 9001

spring:
  application:
    name: blog-user

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka


spring.datasource:
  url: jdbc:mysql://localhost:3306/blog?characterEncoding=UTF-8&useSSL=false
  username: root
  password: root
  driverClassName: com.mysql.jdbc.Driver

spring.jpa.database: MYSQL
spring.jpa.show-sql: true
spring.jpa.hibernate.ddl-auto: update
spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

spring.sleuth.sampler.percentage: 1.0