server:
  port: 9002

spring:
  application:
    name: blog-post
  data:
    mongodb:
      database: blog
      host: 192.168.20.38
#      name: root
#      password: root

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka


spring.sleuth.sampler.percentage: 1.0